package Billy::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Billy::Schema',
    
    connect_info => {
        dsn               => 'dbi:mysql:host=localhost;db=billy',
        user              => 'billy',
        password          => 'billy',
        AutoCommit        => 1,
        RaiseError        => 1,
        mysql_enable_utf8 => 1,
        on_connect_do     => [
            'SET NAMES utf8'
        ],
    }
);

=head1 NAME

Billy::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Billy>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Billy::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=cut

1;
